# Generated by Django 5.2.7 on 2025-11-04 07:49

"""
chatbot 앱 초기 마이그레이션 파일

이 마이그레이션은 ChatMessage 모델을 기반으로
MySQL 데이터베이스에 chat_message 테이블을 생성합니다.

생성 방식:
    python manage.py makemigrations chatbot
    python manage.py migrate

※ Django에서 자동 생성된 파일이며, 직접 수정하지 않는 것을 권장합니다.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("bot", "Bot")], max_length=10
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chat_message",
                "ordering": ["created_at"],
            },
        ),
    ]
