# Generated by Django 5.2.7 on 2025-11-26 16:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, null=True, verbose_name="이름"),
                ),
                (
                    "gender",
                    models.BooleanField(
                        choices=[(True, "남성"), (False, "여성")],
                        null=True,
                        verbose_name="성별",
                    ),
                ),
                ("age", models.IntegerField(null=True, verbose_name="나이")),
                (
                    "job",
                    models.CharField(
                        choices=[
                            ("학생", "학생"),
                            ("직장인", "직장인"),
                            ("프리랜서", "프리랜서"),
                            ("무직", "무직"),
                            ("주부", "주부"),
                            ("개인사업자", "개인사업자"),
                            ("공무원", "공무원"),
                            ("군인", "군인"),
                            ("기타", "기타"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="직업",
                    ),
                ),
                (
                    "earnings",
                    models.CharField(
                        choices=[
                            ("0원 ~ 1,000만원 미만", "0원 ~ 1,000만원 미만"),
                            (
                                "1,000만원 ~ 3,000만원 미만",
                                "1,000만원 ~ 3,000만원 미만",
                            ),
                            (
                                "3,000만원 ~ 5,000만원 미만",
                                "3,000만원 ~ 5,000만원 미만",
                            ),
                            ("5,000만원 ~ 1억원 미만", "5,000만원 ~ 1억원 미만"),
                            ("1억원 이상", "1억원 이상"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="소득",
                    ),
                ),
                (
                    "life_area",
                    models.CharField(
                        choices=[
                            ("서울특별시", "서울특별시"),
                            ("부산광역시", "부산광역시"),
                            ("인천광역시", "인천광역시"),
                            ("대구광역시", "대구광역시"),
                            ("대전광역시", "대전광역시"),
                            ("광주광역시", "광주광역시"),
                            ("울산광역시", "울산광역시"),
                            ("세종특별자치시", "세종특별자치시"),
                            ("경기도", "경기도"),
                            ("충청북도", "충청북도"),
                            ("충청남도", "충청남도"),
                            ("전라남도", "전라남도"),
                            ("경상북도", "경상북도"),
                            ("경상남도", "경상남도"),
                            ("강원도", "강원도"),
                            ("전북특별자치도", "전북특별자치도"),
                            ("제주도", "제주도"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="거주지역",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
