# Generated by Django 5.2.7 on 2025-11-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="products",
            field=models.ManyToManyField(
                related_name="users", to="products.finproduct"
            ),
        ),
    ]
