# Generated by Django 5.2.7 on 2025-10-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="earnings",
            field=models.CharField(
                choices=[
                    ("0원 ~ 1,000만원 미만", "0원 ~ 1,000만원 미만"),
                    ("1,000만원 ~ 3,000만원 미만", "1,000만원 ~ 3,000만원 미만"),
                    ("3,000만원 ~ 5,000만원 미만", "3,000만원 ~ 5,000만원 미만"),
                    ("5,000만원 ~ 1억원 미만", "5,000만원 ~ 1억원 미만"),
                    ("1억원 이상", "1억원 이상"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.BooleanField(
                choices=[(True, "남성"), (False, "여성")], null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="job",
            field=models.CharField(
                choices=[
                    ("학생", "학생"),
                    ("직장인", "직장인"),
                    ("프리랜서", "프리랜서"),
                    ("무직", "무직"),
                    ("주부", "주부"),
                    ("개인사업자", "개인사업자"),
                    ("공무원", "공무원"),
                    ("군인", "군인"),
                    ("기타", "기타"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="life_area",
            field=models.CharField(
                choices=[
                    ("서울특별시", "서울특별시"),
                    ("부산광역시", "부산광역시"),
                    ("인천광역시", "인천광역시"),
                    ("대구광역시", "대구광역시"),
                    ("대전광역시", "대전광역시"),
                    ("광주광역시", "광주광역시"),
                    ("울산광역시", "울산광역시"),
                    ("세종특별자치시", "세종특별자치시"),
                    ("경기도", "경기도"),
                    ("충청북도", "충청북도"),
                    ("충청남도", "충청남도"),
                    ("전라남도", "전라남도"),
                    ("경상북도", "경상북도"),
                    ("경상남도", "경상남도"),
                    ("강원도", "강원도"),
                    ("전북특별자치도", "전북특별자치도"),
                    ("제주도", "제주도"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
