# Generated by Django 5.2.7 on 2025-10-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="earnings",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="job",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="life_area",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
