# Generated by Django 5.2.7 on 2025-11-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinProduct",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("company_type", models.CharField(max_length=50)),
                ("company_name", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=200)),
                ("product_code", models.CharField(max_length=50)),
                ("maturity_interest", models.TextField(blank=True, null=True)),
                ("conditions", models.TextField(blank=True, null=True)),
                (
                    "join_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "join_target",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("max_limit", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "disclosure_start",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "disclosure_end",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "disclosure_month",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "fin_products",
                "managed": False,
            },
        ),
    ]
