# Generated by Django 5.2.7 on 2025-11-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinProduct",
            fields=[
                (
                    "fin_prdt_cd",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("kor_co_nm", models.CharField(max_length=100, null=True)),
                ("fin_co_no", models.CharField(max_length=50, null=True)),
                ("fin_prdt_nm", models.CharField(max_length=200, null=True)),
                ("join_way", models.CharField(max_length=255, null=True)),
                ("company_type", models.CharField(max_length=50, null=True)),
                ("category", models.CharField(max_length=50, null=True)),
                ("dcls_strt_day", models.CharField(max_length=20, null=True)),
                ("dcls_end_day", models.CharField(max_length=20, null=True)),
                ("dcls_month", models.CharField(max_length=20, null=True)),
                ("description", models.TextField(null=True)),
            ],
            options={
                "db_table": "fin_products",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FixedDepositOption",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("join_member", models.CharField(max_length=255, null=True)),
                ("mtrt_int", models.TextField(null=True)),
                ("spcl_cnd", models.TextField(null=True)),
                ("join_deny", models.CharField(max_length=10, null=True)),
                ("max_limit", models.CharField(max_length=255, null=True)),
                ("intr_rate_type_nm", models.CharField(max_length=255, null=True)),
                ("save_trm", models.CharField(max_length=255, null=True)),
                ("intr_rate", models.TextField(null=True)),
                ("intr_rate2", models.TextField(null=True)),
                ("dcls_month", models.CharField(max_length=20, null=True)),
                (
                    "fin_prdt_cd",
                    models.ForeignKey(
                        db_column="fin_prdt_cd",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_options",
                        to="products.finproduct",
                    ),
                ),
            ],
            options={
                "db_table": "fixed_deposit_option",
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "fin_prdt_cd",
                            "intr_rate_type_nm",
                            "save_trm",
                            "dcls_month",
                        ),
                        name="uq_fixed_deposit_option_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InstallmentDepositOption",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("join_member", models.CharField(max_length=255, null=True)),
                ("mtrt_int", models.CharField(max_length=255, null=True)),
                ("spcl_cnd", models.CharField(max_length=255, null=True)),
                ("join_deny", models.CharField(max_length=10, null=True)),
                ("max_limit", models.CharField(max_length=255, null=True)),
                ("rsrv_type_nm", models.CharField(max_length=255, null=True)),
                ("intr_rate_type_nm", models.CharField(max_length=255, null=True)),
                ("save_trm", models.CharField(max_length=255, null=True)),
                ("intr_rate", models.CharField(max_length=255, null=True)),
                ("intr_rate2", models.CharField(max_length=255, null=True)),
                ("dcls_month", models.CharField(max_length=20, null=True)),
                (
                    "fin_prdt_cd",
                    models.ForeignKey(
                        db_column="fin_prdt_cd",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_options",
                        to="products.finproduct",
                    ),
                ),
            ],
            options={
                "db_table": "installment_deposit_option",
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "fin_prdt_cd",
                            "rsrv_type_nm",
                            "intr_rate_type_nm",
                            "save_trm",
                            "dcls_month",
                        ),
                        name="uq_installment_deposit_option_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JeonseLoanOption",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("loan_inci_expn", models.TextField(null=True)),
                ("erly_rpay_fee", models.TextField(null=True)),
                ("dly_rate", models.TextField(null=True)),
                ("loan_lmt", models.CharField(max_length=255, null=True)),
                ("rpay_type_nm", models.CharField(max_length=255, null=True)),
                ("lend_rate_type_nm", models.CharField(max_length=255, null=True)),
                ("lend_rate_min", models.TextField(null=True)),
                ("lend_rate_max", models.TextField(null=True)),
                ("lend_rate_avg", models.TextField(null=True)),
                ("dcls_month", models.CharField(max_length=20, null=True)),
                (
                    "fin_prdt_cd",
                    models.ForeignKey(
                        db_column="fin_prdt_cd",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jeonse_options",
                        to="products.finproduct",
                    ),
                ),
            ],
            options={
                "db_table": "jeonse_loan_option",
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "fin_prdt_cd",
                            "rpay_type_nm",
                            "lend_rate_type_nm",
                            "dcls_month",
                        ),
                        name="uq_jeonse_loan_option_key",
                    )
                ],
            },
        ),
    ]
